[Setting]
spotify_path           = /home/reazn/.local/share/spotify-launcher/install/usr/share/spotify
prefs_path             = /home/reazn/.config/spotify/prefs
current_theme          = wallust
color_scheme           = wallust
inject_theme_js        = 1
inject_css             = 1
overwrite_assets       = 0
check_spicetify_update = 0
replace_colors         = 1
spotify_launch_flags   = 
always_enable_devtools = 0

[Preprocesses]
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = 
sidebar_config        = 0

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.90.451.gb094aab0
with    = 2.43.2
