-- Hyprland Colors generated by Wallust
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
    active_border = { colors = { "rgb(9BA296)", "rgb(ECA747)" }, angle = 45 },
    inactive_border = "rgba(A9A895aa)",
}
