--###########################
--## ENVIRONMENT VARIABLES ###
--###########################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Dark mode for GTK/Qt apps
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

-- Apply dark mode preference via gsettings (GNOME/GTK portal)

hl.on("hyprland.start", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark")
end)
