-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.monitor({
    output = "DP-1",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
require("programs")

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

-- #############################
-- ### SOURCES #################
-- #############################

-- Source: /home/reazn/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")
-- Source: /home/reazn/.config/hypr/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("env")
-- Source: /home/reazn/.config/hypr/startup.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("startup")
-- Source: /home/reazn/.config/hypr/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("general")
-- Source: /home/reazn/.config/hypr/decorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("decorations")
-- Source: /home/reazn/.config/hypr/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("animations")
-- Source: /home/reazn/.config/hypr/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("misc")
-- Source: /home/reazn/.config/hypr/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("rules")
-- Source: /home/reazn/.config/hypr/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")
