--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local programs = require("programs")
local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local Alt = "ALT"       -- For readability in binds using ALT

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(programs.terminal))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(programs.fileManager))
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + S", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("vicinae toggle"))
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("vicinae vicinae://launch/clipboard/history"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("helium-browser"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("zeditor"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("t3code-nightly"))
hl.bind(mainMod .. " + ALT + D", hl.dsp.exec_cmd("element-desktop-nightly & vesktop"))
hl.bind(mainMod .. " + ALT + G", hl.dsp.exec_cmd("spotify-launcher"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Special workspaces (scratchpads)
hl.bind(mainMod .. " + D", hl.dsp.workspace.toggle_special("messenger"))
hl.bind(mainMod .. " + G", hl.dsp.workspace.toggle_special("music"))
hl.bind(mainMod .. " + Q", hl.dsp.workspace.toggle_special("dev"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.window.move({ workspace = "special:messenger" }))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.window.move({ workspace = "special:music" }))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.move({ workspace = "special:dev" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Screenshot
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region -z"))

-- Screen recording
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("/home/reazn/.config/hypr/scripts/record-region.sh"))

-- Color Picker
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a -n"))

-- Nightlight temperature controls
hl.bind(mainMod .. " + CTRL + N", hl.dsp.exec_cmd("hyprctl hyprsunset temperature +500"))
hl.bind(mainMod .. " + CTRL + SHIFT + N", hl.dsp.exec_cmd("hyprctl hyprsunset temperature -500"))

-- Toggle notifications panel
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("quickshell ipc call bar toggleNotifications"))

-- Toggle workspace overview
hl.bind(Alt .. " + Tab", hl.dsp.exec_cmd("quickshell ipc call bar toggleWorkspaceOverview"))

--###########################################
--## DYNAMIC ULTRAWIDE LAYOUT CONTROLLER  ###
--###########################################

local regional_workspaces = {} -- Tracks regionally constrained workspaces
local focused_2560_workspaces = {} -- Tracks 2560x1440 centered workspaces

-- Toggle Behavior: Regional centering constraint (SUPER + X)
local function toggle_center_region()
    local ws = hl.get_active_workspace()
    local id = tostring(ws.id)

    if regional_workspaces[id] then
        -- Disable: Reset gapsout for the workspace
        hl.workspace_rule({ workspace = id, gaps_out = 0 })
        regional_workspaces[id] = nil
        focused_2560_workspaces[id] = nil
        hl.exec_cmd("notify-send 'Ultrawide Layout' 'Regional constraint: DISABLED'")
    else
        -- Enable: Set 600px left/right margins for all tiled windows
        hl.workspace_rule({ workspace = id, gaps_out = { left = 600, right = 600 } })
        regional_workspaces[id] = true
        focused_2560_workspaces[id] = nil
        hl.exec_cmd("notify-send 'Ultrawide Layout' 'Regional constraint: ENABLED (600px sides)'")
    end
end

-- Toggle Behavior: 2560x1440 centered constraint (SUPER + ALT + X)
local function toggle_2560_region()
    local ws = hl.get_active_workspace()
    local id = tostring(ws.id)

    if focused_2560_workspaces[id] then
        hl.workspace_rule({ workspace = id, gaps_out = 0 })
        focused_2560_workspaces[id] = nil
        hl.exec_cmd("notify-send 'Ultrawide Layout' 'Regional constraint: DISABLED'")
    else
        hl.workspace_rule({ workspace = id, gaps_out = { left = 1280, right = 1280 } })
        focused_2560_workspaces[id] = true
        regional_workspaces[id] = nil
        hl.exec_cmd("notify-send 'Ultrawide Layout' 'Regional constraint: 2560x1440'")
    end
end

-- Bind the toggle
hl.bind(mainMod .. " + X", toggle_center_region)
hl.bind(mainMod .. " + ALT + X", toggle_2560_region)
