-- https://wiki.hypr.land/Configuring/Variables/#misc
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.gesture({
    fingers = 4,
    direction = "horizontal",
    action = "workspace",
    scale = 2.0,
})

-- 4-finger swipe up/down -> toggle workspace overview (same as Alt+Tab).
hl.gesture({
    fingers = 4,
    direction = "up",
    action = function()
        hl.exec_cmd("quickshell ipc call bar toggleWorkspaceOverview")
    end,
})

hl.gesture({
    fingers = 4,
    direction = "down",
    action = function()
        hl.exec_cmd("quickshell ipc call bar toggleWorkspaceOverview")
    end,
})

-- Zoom in/out with a 4-finger pinch (Hyprland cursor magnifier).
hl.gesture({
    fingers = 4,
    direction = "pinch",
    action = "cursorZoom",
    zoom_level = 1,
    mode = "live",
})

-- Block 2-finger pinch so apps (e.g. browsers) can't zoom with 2 fingers.
-- Only the 4-finger pinch above will zoom. Note: this also disables 2-finger
-- pinch in image viewers, PDF readers, etc.
hl.gesture({
    fingers = 2,
    direction = "pinch",
    action = function() end,
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.config({
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
    --##############
    --## INPUT ###
    --##############
    -- https://wiki.hypr.land/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "cz_sk_de",
        kb_model = "",
        kb_options = "caps:super",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
    --##############
    --## GESTURES ###
    --##############
    -- https://wiki.hypr.land/Configuring/Basics/Variables/#gestures
    -- Note: workspace_swipe / workspace_swipe_fingers were removed in 0.55.
    --       Use explicit hl.gesture() calls above instead.
    gestures = {
        workspace_swipe_distance = 300,
        workspace_swipe_forever = true,
        workspace_swipe_cancel_ratio = 0.3,
        workspace_swipe_min_speed_to_force = 30,
    },
    -- See https://wiki.hypr.land/Configuring/Gestures
    -- Example per-device config
    -- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
    xwayland = {
        force_zero_scaling = true,
    },
})
