-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrule {
--     name = no-gaps-wtv1
--     match:float = false
--     match:workspace = w[tv1]
--
--     border_size = 0
--     rounding = 0
-- }
--
-- windowrule {
--     name = no-gaps-f1
--     match:float = false
--     match:workspace = f[1]
--
--     border_size = 0
--     rounding = 0
-- }

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    -- Ignore maximize requests from all apps. You'll probably like this.
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    -- Fix some dragging issues with XWayland
    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

hl.layer_rule({
    name = "vicinae-blur",
    match = {
        namespace = "vicinae",
    },
    blur = true,
    ignore_alpha = 0,
})

hl.layer_rule({
    name = "quickshell-blur",
    match = {
        namespace = "quickshell",
    },
    blur = true,
    ignore_alpha = 0,
})

--#############################
--## WORKSPACE ASSIGNMENTS  ###
--#############################

-- Workspace 1: Editors & IDEs
hl.window_rule({
    match = {
        class = "zeditor|zed|zed-preview|zed-editor|code|code-oss|vscodium|codium|vscode|vs-code|vsc",
    },
    workspace = "1 silent",
})

hl.window_rule({
    match = {
        class = "jetbrains-.*|android-studio",
    },
    workspace = "1 silent",
})

-- Workspace 2: Browsers
hl.window_rule({
    match = {
        class =
        "helium-browser|helium-preview|helium|net\\.imput\\.helium|zen-browser|zen|zen-alpha|firefox|librewolf|chromium",
    },
    workspace = "2 silent",
})

-- Workspace 3: SPARE

-- Workspace 4: Office
hl.window_rule({
    match = {
        class = "libreoffice|soffice|soffice\\.bin",
    },
    workspace = "4 silent",
})

--#############################
--##  SPECIAL WORKSPACES    ###
--#############################

-- Messenger scratchpad (toggle with mainMod + d)
hl.window_rule({
    match = {
        class = "vesktop|element-desktop|Element|im\\.riot\\.Riot|discord|Discord|webcord|WebCord",
    },
    workspace = "special:messenger",
})

-- Music scratchpad (toggle with mainMod + g)
hl.window_rule({
    match = {
        class = "spotify|Spotify|spicetify|feishin|app\\.feishin\\.Feishin|ncspotify|vleer|vleer-preview|vleer-git",
    },
    workspace = "special:music",
})

-- Dev scratchpad (toggle with mainMod + q)
hl.window_rule({
    match = {
        class =
        "t3code|T3Code|T3code-preview|T3Code-Preview|t3code\\.preview|t3code-preview|claude|claude-preview|claude\\.preview|claude-preview|codex|codex-preview|codex\\.preview|codex-preview",
    },
    workspace = "special:dev",
})
