--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("sh -lc 'sleep 2; pgrep -fx \"/home/reazn/.config/quickshell/helpers/localsend-bridge/target/release/localsend-bridge --auto-accept\" >/dev/null || /home/reazn/.config/quickshell/helpers/localsend-bridge/target/release/localsend-bridge --auto-accept >/tmp/localsend-bridge.log 2>&1 &'")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
end)
